export const GET_ANNOUNCEMENTS_BEGIN = "GET_ANNOUNCEMENTS_BEGIN";
export const GET_ANNOUNCEMENTS_SUCCESS = "GET_ANNOUNCEMENTS_SUCCESS";
export const GET_ANNOUNCEMENTS_ERROR = "GET_ANNOUNCEMENTS_ERROR";

export const HANDLE_ANNOUNCEMENT = "HANDLE_ANNOUNCEMENT";

export const HANDLE_SIDEBAR_INDEX = "HANDLE_SIDEBAR_INDEX";

export const LOGIN_STUDENT_BEGIN = "LOGIN_STUDENT_BEGIN";
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS";
export const LOGIN_STUDENT_ERROR = "LOGIN_STUDENT_ERROR";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const CURRENT_STUDENT_BEGIN = "CURRENT_STUDENT_BEGIN";
export const CURRENT_STUDENT_SUCCESS = "CURRENT_STUDENT_SUCCESS";
export const CURRENT_STUDENT_ERROR = "CURRENT_STUDENT_ERROR";

export const LOGOUT_STUDENT = "LOGOUT_STUDENT";

export const STUDENT_TIMETABLE_BEGIN = "STUDENT_TIMETABLE_BEGIN";
export const STUDENT_TIMETABLE_SUCCESS = "STUDENT_TIMETABLE_SUCCESS";
export const STUDENT_TIMETABLE_ERROR = "STUDENT_TIMETABLE_ERROR";

export const STUDENT_ATTENDANCE_BEGIN = "STUDENT_ATTENDANCE_BEGIN";
export const STUDENT_ATTENDANCE_SUCCESS = "STUDENT_ATTENDANCE_SUCCESS";
export const STUDENT_ATTENDANCE_ERROR = "STUDENT_ATTENDANCE_ERROR";

export const GET_SINGLE_COURSE_BEGIN = "GET_SINGLE_COURSE_BEGIN";
export const GET_SINGLE_COURSE_SUCCESS = "GET_SINGLE_COURSE_SUCCESS";
export const GET_SINGLE_COURSE_ERROR = "GET_SINGLE_COURSE_ERROR";

export const CURRENT_STUDENT_COURSES_BEGIN = "CURRENT_STUDENT_COURSES_BEGIN";
export const CURRENT_STUDENT_COURSES_SUCCESS =
  "CURRENT_STUDENT_COURSES_SUCCESS";
export const CURRENT_STUDENT_COURSES_ERROR = "CURRENT_STUDENT_COURSES_ERROR";

export const GET_DAY_INFO = "GET_DAY_INFO";

export const COURSE_ATTENDENCE_BEGIN = "COURSE_ATTENDENCE_BEGIN";
export const COURSE_ATTENDENCE_SUCCESS = "COURSE_ATTENDENCE_SUCCESS";
export const COURSE_ATTENDENCE_ERROR = "COURSE_ATTENDENCE_ERROR";

export const COURSE_ASSESSMENT_BEGIN = "COURSE_ASSESSMENT_BEGIN";
export const COURSE_ASSESSMENT_SUCCESS = "COURSE_ASSESSMENT_SUCCESS";
export const COURSE_ASSESSMENT_ERROR = "COURSE_ASSESSMENT_ERROR";

export const GET_SINGLE_ASSESSMENT = "GET_SINGLE_ASSESSMENT";

export const STUDENT_NOTIFICATION_BEGIN = "STUDENT_NOTIFICATION_BEGIN";
export const STUDENT_NOTIFICATION_SUCCESS = "STUDENT_NOTIFICATION_SUCCESS";
export const STUDENT_NOTIFICATION_ERROR = "STUDENT_NOTIFICATION_ERROR";

export const DASHBOARD_LOADING_BEGIN = "DASHBOARD_LOADING_BEGIN";
export const DASHBOARD_LOADING_END = "DASHBOARD_LOADING_END";
